branches:
  only:
    - master

image:
  - Visual Studio 2017    
    
install:
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - qmake BasicDSP.pro
  - nmake
  
after_build:
  - ps: |
      Push-AppveyorArtifact release\BasicDSP.exe -FileName BasicDSP.exe
  - ls
  - ls release

#artifacts:
#  - path: release\BasicDSP.exe
#    name: BasicDSP-$(APPVEYOR_REPO_TAG_NAME)
#    type: zip

# See: https://ci.appveyor.com/tools/encrypt
deploy:
  description: 'BasicDSP 64-bit windows binary'
  provider: GitHub
  auth_token:
    secure: AfcsCy2CYmodNEHdPy+DJ4BQXvYdATXLV3m/N2vhq3Xpy7SgauXQ0/t/81TZd2vM
  #artifact: /.*\.zip/              # upload all zip packages to release assets
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
