branches:
  only:
    - master

image:
  - Visual Studio 2017    
    
install:
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - qmake BasicDSP.pro
  - nmake
  
#after_build:

artifacts:
  - path: release\BasicDSP.exe
type: zip

# See: https://ci.appveyor.com/tools/encrypt
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'BasicDSP 64-bit windows binary'
  provider: GitHub
  auth_token:
    secure: KrfGWHTb26AlgQb3nrffO1P0RqhX0O8FLT4DYlhkofgWW9zySIyTTisnD4KoN3MY # your encrypted token from GitHub
  artifact: /.*\.zip/              # upload all zip packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
