branches:
  only:
    - master

image:
  - Visual Studio 2017    
    
install:
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake BasicDSP.pro
  - nmake
  
#after_build:

#artifacts:
#  - path: Output\fastqt-*.exe
#  - path: release
#type: zip